# Generated by Django 4.2.24 on 2025-10-13 20:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('imagem', models.ImageField(upload_to='anuncios/')),
                ('url_destino', models.URLField()),
                ('posicao', models.CharField(help_text='Ex.: entre artigos, sidebar, header', max_length=50)),
                ('responsivo', models.BooleanField(default=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Artigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('conteudo', models.TextField(verbose_name='Conteúdo')),
                ('publicado_em', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Publicado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('destaque', models.BooleanField(default=False, verbose_name='Destaque na Home')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artigos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome da Categoria')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='Nome da Tag')),
            ],
        ),
        migrations.CreateModel(
            name='Recomendacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relevancia', models.FloatField(default=0.0, verbose_name='Relevância')),
                ('artigo_origem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recomendacoes_origem', to='jornal.artigo')),
                ('artigo_recomendado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recomendacoes', to='jornal.artigo')),
            ],
        ),
        migrations.CreateModel(
            name='MenuLateral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('url_customizada', models.URLField(blank=True, null=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jornal.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='ConteudoMultimidia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('video', 'Vídeo'), ('audio', 'Áudio'), ('radio', 'Rádio Ao Vivo')], max_length=20)),
                ('url', models.URLField()),
                ('titulo', models.CharField(blank=True, max_length=255, null=True)),
                ('duracao_segundos', models.PositiveIntegerField(blank=True, null=True)),
                ('artigo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='multimidias', to='jornal.artigo')),
            ],
        ),
        migrations.CreateModel(
            name='AssinanteNewsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('frequencia', models.CharField(choices=[('diaria', 'Diária'), ('semanal', 'Semanal')], default='diaria', max_length=20)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('categorias', models.ManyToManyField(related_name='assinantes', to='jornal.categoria')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assinaturas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='artigo',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artigos', to='jornal.categoria'),
        ),
        migrations.AddField(
            model_name='artigo',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='artigos', to='jornal.tag'),
        ),
    ]
