# Generated by Django 4.2.24 on 2025-10-21 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jornal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anuncio',
            options={'verbose_name': 'Anúncio', 'verbose_name_plural': 'Anúncios'},
        ),
        migrations.AlterModelOptions(
            name='artigo',
            options={'ordering': ['-publicado_em'], 'verbose_name': 'Artigo', 'verbose_name_plural': 'Artigos'},
        ),
        migrations.AlterModelOptions(
            name='assinantenewsletter',
            options={'verbose_name': 'Assinante de Newsletter', 'verbose_name_plural': 'Assinantes de Newsletter'},
        ),
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='conteudomultimidia',
            options={'verbose_name': 'Conteúdo Multimídia', 'verbose_name_plural': 'Conteúdos Multimídia'},
        ),
        migrations.AlterModelOptions(
            name='menulateral',
            options={'ordering': ['ordem'], 'verbose_name': 'Item de Menu Lateral', 'verbose_name_plural': 'Itens de Menu Lateral'},
        ),
        migrations.AlterModelOptions(
            name='recomendacao',
            options={'verbose_name': 'Recomendação', 'verbose_name_plural': 'Recomendações'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
        migrations.AddField(
            model_name='artigo',
            name='subtitulo',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Subtítulo/Resumo'),
        ),
    ]
