# Generated by Django 5.2.6 on 2025-11-18 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jornal', '0002_alter_anuncio_options_alter_artigo_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artigo',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='artigos/'),
        ),
    ]
