# Generated by Django 4.2.26 on 2025-11-25 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jornal', '0003_artigo_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='artigo',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='artigos/videos/%Y/%m/', verbose_name='Vídeo da Matéria'),
        ),
        migrations.AlterField(
            model_name='artigo',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='artigos/imagens/%Y/%m/', verbose_name='Imagem de Capa'),
        ),
    ]
